### ISSUE TITLE
Add support for minimum SDK 14

### ISSUE THREAD

**Issue by vijaemanlapaz** [DeveloperPaul123/SimpleBluetoothLibrary#13]
support toolbar is not supported.

**Comment by ptsouchlos** [comment]
The current minimum sdk for the project is 14. Could you elaborate on what you mean?

**Comment by vijaemanlapaz** [comment]
I used the supportBluetoothActivity
and it always return a window has leaked.

**Comment by ptsouchlos** [comment]
Can you post code and the exact stack trace/error you're getting?

**Comment by ptsouchlos** [comment]
Can you post code and the exact stack trace/error you're getting?
