### ISSUE TITLE
Add Marshmallow support

### ISSUE THREAD

**Issue by ptsouchlos** [DeveloperPaul123/SimpleBluetoothLibrary#16]
Add support for properly handling permission requests for Android API Level 23+.

**Comment by ritdaw** [comment]
Both bluetooth permissions are defined as android:protectionLevel="normal" which means the user doesn't need to grant permission. So no specific Marshmallow changes required for permissions.

**Comment by ptsouchlos** [comment]
Good point. I hadn't looked into this at all. So thanks for that!
