### ISSUE TITLE
Error:Failed to resolve: com.afollestad:material-dialogs:0.6.4.6

### ISSUE THREAD

**Issue by efim-sim-sim** [DeveloperPaul123/SimpleBluetoothLibrary#2]
Hello!
When I write in Gradle:

dependencies {
    compile 'com.github.developerpaul123.simplebluetoothlibrary:library:1.3'
}

I get error: Failed to resolve: com.afollestad:material-dialogs:0.6.4.6

**Comment by ptsouchlos** [comment]
This is a bug with the material dialogs library. I'll be sure to fix it in the next release but for now you can add this to your project buildfile under "allProjects"
repositories {
    maven { url 'https://dl.bintray.com/drummer-aidan/maven' }
}

**Comment by efim-sim-sim** [comment]
Thank You.
