### ISSUE TITLE
Initialize with flag to disable toast messages

### ISSUE THREAD

**Issue by ritdaw** [DeveloperPaul123/SimpleBluetoothLibrary#20]
It would be great if all toast messages could be disabled with a flag when initialized, in certain scenarios we do not want to display messages such as "Device not available." and "Device connected!".

**Comment by ptsouchlos** [comment]
Yeah I recently thought the same thing. I'll do that, and I think I'm going to switch to snackbars as well.

**Comment by ritdaw** [comment]
Great. If you were able to do a quick commit with a flag to disable them for now it would be much appreciated :)

**Comment by ptsouchlos** [comment]
Ok I did a dirty commit. You can find it here: `'com.github.DeveloperPaul123:SimpleBluetoothLibrary:f20764725f'`. I haven't tested this (haven't had time today) so if you could help me out that would be great. I think I'm going to draft a new release at this point and push off the BluetoothService feature. Keep the suggestions coming I want to make this library as great and comprehensive as possible.

**Comment by ptsouchlos** [comment]
Commit f20764725f11a1091dd578fe4247b6aac7de224a closes #20

**Comment by ptsouchlos** [comment]
Let me know if it works if you get a chance and I'll draft the v1.5 release.

**Comment by ritdaw** [comment]
Thanks, I'll try it this afternoon.

**Comment by ritdaw** [comment]
Works perfectly, tried without using setShouldShowSnackbars and they show and then used setShouldShowSnackbars(false) and they don't show as intended.

It might be worth doing a release without the service in the interim.

**Comment by ptsouchlos** [comment]
Fantastic! And yes i'm going to save that for a future release along with allowing for multiple connections on a bluetoothserver connection. Thanks for all your help.
