### ISSUE TITLE
Update support library 23.2.0

### ISSUE THREAD

**Issue by Nanuqac** [DeveloperPaul123/SimpleBluetoothLibrary#21]
Hi, could I ask you to update the library _com.github.afollestad.material-dialogs_ because this library refers to the resource _@drawable/abc_ic_ab_back_mtrl_am_alpha_ and this resource in support library 23.2.0 was renamed to _@drawable/abc_ic_ab_back_material_. When I tried to update support library I cannot build my app.

Thanks a lot

**Comment by ptsouchlos** [comment]
Sure thing. I'll do that hopefully today. Sorry about that.

**Comment by ptsouchlos** [comment]
Just released a new version with the updated library. Let me know if it fixed it.

**Comment by Nanuqac** [comment]
Yes it works, thank you.

**Comment by ptsouchlos** [comment]
Could I ask that you let me know what app you're developing so I can start an app list that use this library in the Readme?

**Comment by Nanuqac** [comment]
Hi, I use the library for application to the warehouse where I needed to connect a barcode scanner. Unfortunately, the application is not on Google Play. Thanks for the library, has saved me a lot of time.

**Comment by ptsouchlos** [comment]
Oh ok cool. No worries then. And great! Glad it helped.
