### ISSUE TITLE
incomplete data

### ISSUE THREAD

**Issue by smilecs** [DeveloperPaul123/SimpleBluetoothLibrary#22]
i seem to be getting incomplete data string when passing a string concatenated with a base64 image. The base64 data is sent partial. e.g String1+":"+"String2+":"+base64image

**Comment by ptsouchlos** [comment]
Can I see the code you are using to send the image? What exactly is missing from the message you are sending?

**Comment by ptsouchlos** [comment]
Is the issue similar to #14 ?

**Comment by smilecs** [comment]
yes its similar....i will send the code...

**Comment by smilecs** [comment]
here's the code

`     simpleBluetooth.initializeSimpleBluetooth();
        simpleBluetooth.setInputStreamType(BluetoothUtility.InputStreamType.BUFFERED);
        simpleBluetooth.setSimpleBluetoothListener(new SimpleBluetoothListener() {

```
        @Override
        public void onBluetoothDataReceived(byte[] bytes, String data) {
            //Log.d(TAG + "incoming data", data);
           // result = result + data;
            //db.AddFriend(fp.friend());
            Log.d(TAG, data);
            try{
                toParse = data.split(":");
                byte[] im = Base64.decode(toParse[4], Base64.CRLF);
                Log.d("decoder", "decoder");
                Bitmap bit = BitmapFactory.decodeByteArray(im, 0, im.length);
            }catch (Exception e){
                e.printStackTrace();
            }
            //friendParser fp = new friendParser(result);
            //Log.d(TAG, String.valueOf(bytes.length));
            isConnected=false;

            //read the data coming in.
        }
```

`

**Comment by ptsouchlos** [comment]
Thanks for the code. 

I would try this without using the buffered stream type. When you set the stream type to buffered, the library will be looking for a newline character and will not report the results in `onBluetoothDataReceived` until a new line character is reached which is more than likely why you're losing data since I'm assuming there is no `\n` in your image data. 

Try that and update this issue with the results.

**Comment by smilecs** [comment]
ok thanks very much..i'll do that

**Comment by smilecs** [comment]
I tested the solution it gives the full data when i added the escape character `\n` but i noticed that while the data is being read it overrides the previous data argument on the received method. Is there a way it can send the data after all has been collected? my work around was to create a global string which i concatenate the data received to the global variable. Heres the code 
` simpleBluetooth.initializeSimpleBluetooth();
        simpleBluetooth.setInputStreamType(BluetoothUtility.InputStreamType.BUFFERED);
        simpleBluetooth.setSimpleBluetoothListener(new SimpleBluetoothListener() {

```
        @Override
        public void onBluetoothDataReceived(byte[] bytes, String data) {
            //Log.d(TAG + "incoming data", data);
           result = result + data;
            //db.AddFriend(fp.friend());
            Log.d(TAG, data);

            toParse = result.split(":");
            Log.d(TAG, String.valueOf(toParse.length));
            i = toParse.length;

            if(i == 6){
                Log.d(TAG, "called");
              try{
                    Log.d(TAG, "called");
                  friendParser fp = new friendParser(result);
                  db.AddFriend(fp.friend());
                   /*toParse = data.split("LIFE");
                    byte[] im = Base64.decode(toParse[4], Base64.CRLF);
                    Bitmap bit = BitmapFactory.decodeByteArray(im, 0, im.length);
                */
                }catch (Exception e){
                    e.printStackTrace();
                }

            }
```

`

**Comment by ptsouchlos** [comment]
Maybe I wasn't clear in my previous post. What I meant to do is change the line: 
`simpleBluetooth.setInputStreamType(BluetoothUtility.InputStreamType.BUFFERED);` to the following:
`simpleBluetooth.setInputStreamType(BluetoothUtility.InputStreamType.NORMAL);`

**Comment by ptsouchlos** [comment]
Did that work?

**Comment by smilecs** [comment]
yes it did, sorry was suppose to close the issue. thanks for the support

SmileCs past3.com.ng

**Comment by ptsouchlos** [comment]
No problem. Thanks for using my lib.
