### ISSUE TITLE
BluetoothUtility.closeConnections() crashes

### ISSUE THREAD

**Issue by KnightHill** [DeveloperPaul123/SimpleBluetoothLibrary#24]
BluetoothUtility.closeConnections() crashes when called with a connected BT device. The call looks like this:
`BluetoothUtility bu = simpleBluetooth.getBluetoothUtility();`
`bu.closeConnections();`

Tracing shows calling the close method of the Connected thread causes a problem:
`public void cancel() {`
`try {`
`this.mmSocket.close();`
`} catch (IOException var2) {`
`;`
`}`
        }`

**Comment by ptsouchlos** [comment]
Was this resolved? Is that why you closed it?

**Comment by KnightHill** [comment]
No, I closed it because I wasn't 100% sure this is not because of improper activity life-cycle management. However, this may be worth taking a look.

**Comment by ptsouchlos** [comment]
Do you mean improper life cycle management on the part of the library? Or in how you used the `BluetoothUtility` class?
