### ISSUE TITLE
Data Lossed with arduino 

### ISSUE THREAD

**Issue by thedavekwon** [DeveloperPaul123/SimpleBluetoothLibrary#29]
Hi, this is Dave. 
Is there anyway to prevent data loss when connected to an arduino with bluetooth?
I have connected arduino to my galaxy s6 edge. 
It works fine with the bluetooth Serial application, but I couldn't figure it out why.

**Comment by ptsouchlos** [comment]
Can you share the code you're using on both the android and arduino side?

**Comment by thedavekwon** [comment]
I was doing a project with a time limit, so I am currently using another library. 
The code was basically, sending data via bluetooth using software serial. And little modification of sample code. I tried both buffered and normal settings.

**Comment by ptsouchlos** [comment]
I see, would you at least be willing to post the arduino code so I can replicate the issue?

**Comment by thedavekwon** [comment]
Basically, it was with software serial.

Serial.begin(9600);
delay(200);
bluetooth.begin(115200);
bluetooth.print("$");  
bluetooth.print("$");
bluetooth.print("$");  
delay(200);  
bluetooth.println("U,9600,N");
bluetooth.begin(9600);
bluetooth.setTimeout(10);

and after initializing and collecting data from sensor. 
output = String(beatAvg) + "," + String(temp) + "," + String(ptt) + "," + String(gsr_average);
bluetooth.println(output);

I was using arduino nano for my device!

**Comment by ptsouchlos** [comment]
May I ask why you're initializing the `bluetooth` communication twice and with different baud rates?

**Comment by thedavekwon** [comment]
I wanted to change baud rate, but I already soldered everything together. And I saw in the Sparkfun tutorial that I could change baud rate using this method. I  also tried with single "bluetooth.begin(115200)" too, but it gave me same result.
